### ISSUE TITLE
win8 x64 on subl init error

### ISSUE THREAD

**Issue by AuthorProxy** [timonwong/SublimeAStyleFormatter#15]
reloading plugin SublimeAStyleFormatter.AStyleFormat
Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 2, in <module>
    import sublime
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._local_arch.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 6, in <module>

ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._linux_libcpp6_x86_64.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 10, in <module>
    HTML                      = 'text.html - source'
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._linux_libcpp6_x86.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 14, in <module>
    HTML_INSIDE_TAG           = ( 'text.html meta.tag - string - '
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._win64.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 18, in <module>
    HTML_INSIDE_TAG_ATTRIBUTE = 'text.html meta.tag string'
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._win32.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 22, in <module>
    NO_PLUG = sublime.INHIBIT_EXPLICIT_COMPLETIONS
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._macosx_universal.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\AStyleFormat.py", line 34, in <module>
  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle__init__.py", line 6, in <module>

  File "C:\Documents\Software\Programming\IDE\SublimeText\SublimeText3\Data\Installed Packages\SublimeAStyleFormatter.sublime-package\pyastyle\python3__init__.py", line 25, in <module>
    EMMET_SCOPE = ', '.join([HTML, XML])
ImportError: Could not find a suitable pyastyle binary for your platform and architecture.

**Comment by vowstar** [comment]
#61 Have the same problem.
