### ISSUE TITLE
Not working on windows 10/Sublie Text 3

### ISSUE THREAD

**Issue by Solaris0627** [timonwong/SublimeAStyleFormatter#61]
reloading plugin SublimeAStyleFormatter.AStyleFormat
Traceback (most recent call last):
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 2, in <module>
    from ._local_arch.pyastyle import *
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._local_arch.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 6, in <module>
    from ._linux_x86_64.pyastyle import *
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._linux_x86_64.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 10, in <module>
    from ._linux_x86.pyastyle import *
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._linux_x86.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 14, in <module>
    from ._win64.pyastyle import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 18, in <module>
    from ._win32.pyastyle import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 22, in <module>
    from ._macosx_universal.pyastyle import *
ImportError: No module named 'SublimeAStyleFormatter.pyastyle.python3._macosx_universal.pyastyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module

  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\AStyleFormat.py", line 35, in <module>
    from . import pyastyle
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle__init__.py", line 6, in <module>
    from .python3 import *
  File "C:\Users\derek\AppData\Roaming\Sublime Text 3\Packages\SublimeAStyleFormatter\pyastyle\python3__init__.py", line 25, in <module>
    raise ImportError("Could not find a suitable pyastyle binary for your platform and architecture.")
ImportError: Could not find a suitable pyastyle binary for your platform and architecture.

**Comment by vowstar** [comment]
I have tried sublime 32bit and 64bit 3083, it have same problem.

**Comment by vowstar** [comment]
@Solaris0627 ;)  I found the solution, pyastyle for windows  64 depends on
 Microsoft Visual C++ 2010 SP1 Redistributable Package (x64)
So just download and install it, and every thing is OK.
See also: 
#15

**Comment by canfoderiskii** [comment]
@vowstar thanks for your solution, it solved my problem too.

**Comment by mjmoore** [comment]
@vowstar @canforderiskii Also solved the issue for me. Thanks.

**Comment by BJKhunt** [comment]
@vowstar thanks for solution ...

**Comment by Arkenite03** [comment]
Worked for me too! Thanks @vowstar

**Comment by wery0** [comment]
Thanks @vowstar, your solution is still working on win11!
